"""Weekly news digest sourcing via Google News RSS (free, no API key).

Pulls recent headlines for Boot Barn and its competitors and renders a clean,
research-note-style HTML email. Used by weekly_digest.py and the dashboard's
News tab.
"""
from __future__ import annotations

import datetime as dt
import html
import urllib.parse

import feedparser

DEFAULT_COMPANIES = ["Boot Barn", "Ariat", "Cavender's", "Tecovas",
                     "Tractor Supply", "Sheplers"]


def _clean_title(title: str, source: str) -> str:
    """Google appends ' - Source' to titles; strip it for a clean headline."""
    if source and title.endswith(f" - {source}"):
        title = title[: -(len(source) + 3)]
    return title.strip()


def fetch_news(company: str, days: int = 7, limit: int = 6) -> list[dict]:
    q = urllib.parse.quote(f'"{company}" when:{days}d')
    url = f"https://news.google.com/rss/search?q={q}&hl=en-US&gl=US&ceid=US:en"
    feed = feedparser.parse(url)
    out, seen = [], set()
    for e in feed.entries:
        source = getattr(getattr(e, "source", None), "title", "") or ""
        title = _clean_title(getattr(e, "title", ""), source)
        key = title.lower()
        if not title or key in seen:
            continue
        seen.add(key)
        pub = None
        if getattr(e, "published_parsed", None):
            pub = dt.datetime(*e.published_parsed[:6])
        out.append({"title": title, "link": getattr(e, "link", ""),
                    "source": source, "published": pub})
        if len(out) >= limit:
            break
    return out


def gather(companies: list[str] | None = None, days: int = 7,
           limit: int = 6) -> dict[str, list[dict]]:
    return {c: fetch_news(c, days, limit) for c in (companies or DEFAULT_COMPANIES)}


def _fmt_date(pub) -> str:
    return pub.strftime("%b %d") if isinstance(pub, dt.datetime) else ""


def build_digest_html(data: dict[str, list[dict]], days: int = 7) -> str:
    """Clean, professional research-note styling (inline CSS for email clients)."""
    now = dt.datetime.now().strftime("%B %d, %Y")
    navy, amber, ink, mut = "#1f3a5f", "#c8891f", "#1a1a1a", "#6b7280"
    parts = [
        f'<div style="max-width:640px;margin:0 auto;font-family:Georgia,\'Times '
        f'New Roman\',serif;color:{ink};line-height:1.5;">',
        f'<div style="border-bottom:3px solid {amber};padding-bottom:10px;'
        f'margin-bottom:18px;">'
        f'<div style="font-size:22px;font-weight:bold;color:{navy};">Western &amp; '
        f'Workwear Retail — Weekly Brief</div>'
        f'<div style="font-size:13px;color:{mut};margin-top:3px;">Week of {now} '
        f'· Boot Barn (BOOT) &amp; competitors · past {days} days</div></div>',
    ]
    for company, items in data.items():
        parts.append(
            f'<div style="font-size:16px;font-weight:bold;color:{navy};'
            f'border-left:4px solid {amber};padding-left:8px;margin:18px 0 8px;">'
            f'{html.escape(company)}</div>')
        if not items:
            parts.append(f'<div style="font-size:13px;color:{mut};padding-left:12px;">'
                         'No notable news this week.</div>')
            continue
        parts.append('<ul style="margin:0;padding-left:20px;">')
        for it in items:
            meta = " · ".join(x for x in (html.escape(it["source"]),
                                          _fmt_date(it["published"])) if x)
            parts.append(
                f'<li style="margin-bottom:9px;font-size:14px;">'
                f'<a href="{html.escape(it["link"])}" '
                f'style="color:{navy};text-decoration:none;">{html.escape(it["title"])}</a>'
                f'<span style="color:{mut};font-size:12px;"> — {meta}</span></li>')
        parts.append('</ul>')
    parts.append(
        f'<div style="border-top:1px solid #e5e7eb;margin-top:22px;padding-top:10px;'
        f'font-size:11px;color:{mut};">Auto-generated by Boot Barn X-Ray from public '
        'Google News results. Headlines link to original sources.</div></div>')
    return "\n".join(parts)


def build_digest_text(data: dict[str, list[dict]]) -> str:
    lines = ["Western & Workwear Retail — Weekly Brief", ""]
    for company, items in data.items():
        lines.append(f"## {company}")
        if not items:
            lines.append("  (no notable news this week)")
        for it in items:
            meta = " · ".join(x for x in (it["source"], _fmt_date(it["published"])) if x)
            lines.append(f"  - {it['title']} — {meta}\n    {it['link']}")
        lines.append("")
    return "\n".join(lines)
